### ISSUE TITLE
3D printing parts and Ferrite ring

### ISSUE THREAD

**Issue by Tomatendose** [westonb/little-bee-B1#1]
Hi,

I can't find any technical documents for the 3D printed parts and the ferrite ring. Is it possible to provide them? 

Greetings

**Comment by westonb** [comment]
Added STL files for the 3d printed parts and information on required fasteners and the ferrite core for the flux concentrator. 

https://github.com/westonb/little-bee-B1/tree/main/mcad

**Comment by smarley2** [comment]
> Added STL files for the 3d printed parts and information on required fasteners and the ferrite core for the flux concentrator.
> 
> https://github.com/westonb/little-bee-B1/tree/main/mcad

Where this Fair Rite PN can be ordered with the Gap?

Thanks!
